# Generated by Django 5.0.3 on 2024-04-13 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.product",
            ),
        ),
    ]
